### PR TITLE
Added logging, & small fixes

### PR DESCRIPTION
**Pull request by ericfinger**
Replaced print() statements with proper logging. 

Also adjusted 2 small things:
- ``restore_reaction_roles()``: moved ``role`` variable out of ``member`` loop (bc it's an uneccesary lookup every loop)
- Added documentation to selfrole-functions

### CODE REVIEW

**Comment by tobb10001** [comment]
I don't know if it matters much here, but using `logging.info()` or something else on `logging` directly is kinda discuraged because it uses the root logger. A better pattern is to use a logger that is specific for the actual module and therefore provides the possibility to control logging behaviour for specific modules.

The way this is done is:
```py
import logging

logger = logging.getLogger(__name__)

# and do everything as before, but replacing `logging` with `logger`
logger.info(...)
```
Source: https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial

**Comment by ericfinger** [comment]
I really don't think it matters here but sure, that's easy enough to do

**Comment by ericfinger** [comment]
(also removed the unused re import)

**Comment by friedrichgross** [comment]
please github email next time

**Pull request merged**
