### PR TITLE
Added Kick and ban, works fine, now just needs to be optimized to give random scentences on ban or Kick

### PR DESCRIPTION
**Pull request by BlackyPurp**
This time without file change <3

### CODE REVIEW

**Comment by tobb10001** [comment]
Can't say much about the functionality itself, but you managed to fit the pattern I introduced well. 👍🏽

Only would recommend you to write less title and more description for your next PR. 🙂

EDIT: **more** description. Don't write while talking to somebody else. 🤦🏽‍♂️

**Comment by BlackyPurp** [comment]
Will try to make more Desc.less Title :)

**Comment by BlackyPurp** [comment]
Found a bug in Ban function. Will send new PR with fixed Ban

**Comment by tobb10001** [comment]
You could've just push another commit to this branch. The PR will update automatically, so you don't need to make a new one.

**Comment by BlackyPurp** [comment]
Didn't want to publish bugged code.

**Pull request closed without merging**
